FROM node:19-bullseye

WORKDIR /usr/src/app
COPY socket-server/* ./
COPY /util/token-validate.ts .
COPY socket-server-cert.pem .
COPY socket-server-key.pem .

# Expose the websocket server
EXPOSE 8443
# Expose the TCP serer
EXPOSE 8080

# Install dependencies
RUN yarn
RUN yarn global add pm2

# Compile the app
RUN yarn tsc

ENV NODE_ENV=production
CMD ["pm2-runtime", "socket-server.js"]
