FROM node:18-bullseye

WORKDIR /usr/src/app
COPY socket-server/* ./
COPY /util/token-validate.ts .
COPY socket-server-cert.pem .
COPY socket-server-key.pem .
EXPOSE 8443
RUN yarn
RUN yarn global add pm2

ENV NODE_ENV=production
CMD ["pm2-runtime", "socket-server.js"]
