version: '3.1'

services:

  db:
    env_file:
    - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"

  socket-server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.socket-server
    ports:
      - "8080:8080"
      - "8443:8443"
