version: '3.1'

services:

  db:
    env_file:
    - .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
